# Generated by Django 5.0.7 on 2024-07-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='purchaserecord',
            table='purchaseRecord',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
    ]
