# Generated by Django 5.0.7 on 2025-03-01 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_purchaserecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipts.item'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipts.store'),
        ),
    ]
